version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: smartmeter
      POSTGRES_PASSWORD: smartmeter123
      POSTGRES_DB: smartmeter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartmeter"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./exports:/app/exports
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://smartmeter:smartmeter123@postgres:5432/smartmeter_db
      REDIS_URL: redis://redis:6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./app:/app/app
      - ./exports:/app/exports
    environment:
      DATABASE_URL: postgresql://smartmeter:smartmeter123@postgres:5432/smartmeter_db
      REDIS_URL: redis://redis:6379
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data: 